"""Реализовал модель 'Пользователь'

Revision ID: 8204edaf040a
Revises: 
Create Date: 2023-12-11 23:07:42.036891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8204edaf040a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserBase',
    sa.Column('fullname', sa.String(length=100), nullable=False),
    sa.Column('group', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('isCurrentEmployee', sa.Boolean(), nullable=False),
    sa.Column('isEnabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_UserBase_email'), 'UserBase', ['email'], unique=False)
    op.create_index(op.f('ix_UserBase_fullname'), 'UserBase', ['fullname'], unique=False)
    op.create_index(op.f('ix_UserBase_group'), 'UserBase', ['group'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_UserBase_group'), table_name='UserBase')
    op.drop_index(op.f('ix_UserBase_fullname'), table_name='UserBase')
    op.drop_index(op.f('ix_UserBase_email'), table_name='UserBase')
    op.drop_table('UserBase')
    # ### end Alembic commands ###
